name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Install dependencies
        run: |
          terraform init

      - name: Apply Terraform changes
        run: |
          terraform apply -auto-approve
        env:
          TF_VAR_your_variable: ${{ secrets.YOUR_SECRET_VARIABLE }}  # If you need sensitive variables
