name: Terraform PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7' 

      - name: Install dependencies
        run: |
          terraform init

      - name: Run Terraform plan
        run: |
          terraform plan
